//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTest.BookingTool {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="BookingTool.BookingTool")]
    public interface BookingTool {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BookingTool/Booking", ReplyAction="urn:BookingTool/BookingResponse")]
        void Booking(int bookingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BookingTool/Booking", ReplyAction="urn:BookingTool/BookingResponse")]
        System.Threading.Tasks.Task BookingAsync(int bookingId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookingToolChannel : ConsoleTest.BookingTool.BookingTool, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingToolClient : System.ServiceModel.ClientBase<ConsoleTest.BookingTool.BookingTool>, ConsoleTest.BookingTool.BookingTool {
        
        public BookingToolClient() {
        }
        
        public BookingToolClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingToolClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingToolClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingToolClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Booking(int bookingId) {
            base.Channel.Booking(bookingId);
        }
        
        public System.Threading.Tasks.Task BookingAsync(int bookingId) {
            return base.Channel.BookingAsync(bookingId);
        }
    }
}
