//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.BookingHouse {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="BookingHouse.BookingHouse")]
    public interface BookingHouse {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BookingHouse/Booking", ReplyAction="urn:BookingHouse/BookingResponse")]
        void Booking(int bookingHouseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BookingHouse/Booking", ReplyAction="urn:BookingHouse/BookingResponse")]
        System.Threading.Tasks.Task BookingAsync(int bookingHouseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BookingHouse/BrokerConfirmBooking", ReplyAction="urn:BookingHouse/BrokerConfirmBookingResponse")]
        void BrokerConfirmBooking(int bookingHouseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BookingHouse/BrokerConfirmBooking", ReplyAction="urn:BookingHouse/BrokerConfirmBookingResponse")]
        System.Threading.Tasks.Task BrokerConfirmBookingAsync(int bookingHouseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BookingHouse/UserConfirmBooking", ReplyAction="urn:BookingHouse/UserConfirmBookingResponse")]
        void UserConfirmBooking(int bookingHouseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BookingHouse/UserConfirmBooking", ReplyAction="urn:BookingHouse/UserConfirmBookingResponse")]
        System.Threading.Tasks.Task UserConfirmBookingAsync(int bookingHouseId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookingHouseChannel : ConsoleApplication1.BookingHouse.BookingHouse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingHouseClient : System.ServiceModel.ClientBase<ConsoleApplication1.BookingHouse.BookingHouse>, ConsoleApplication1.BookingHouse.BookingHouse {
        
        public BookingHouseClient() {
        }
        
        public BookingHouseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingHouseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingHouseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingHouseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Booking(int bookingHouseId) {
            base.Channel.Booking(bookingHouseId);
        }
        
        public System.Threading.Tasks.Task BookingAsync(int bookingHouseId) {
            return base.Channel.BookingAsync(bookingHouseId);
        }
        
        public void BrokerConfirmBooking(int bookingHouseId) {
            base.Channel.BrokerConfirmBooking(bookingHouseId);
        }
        
        public System.Threading.Tasks.Task BrokerConfirmBookingAsync(int bookingHouseId) {
            return base.Channel.BrokerConfirmBookingAsync(bookingHouseId);
        }
        
        public void UserConfirmBooking(int bookingHouseId) {
            base.Channel.UserConfirmBooking(bookingHouseId);
        }
        
        public System.Threading.Tasks.Task UserConfirmBookingAsync(int bookingHouseId) {
            return base.Channel.UserConfirmBookingAsync(bookingHouseId);
        }
    }
}
